// <auto-generated/>
#pragma warning disable 1591
#pragma warning disable 0414
#pragma warning disable 0649
#pragma warning disable 0169

namespace EADCA3.Pages
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Components;
#nullable restore
#line 1 "C:\Users\malia\source\repos\EADCA3\EADCA3\_Imports.razor"
using System.Net.Http;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "C:\Users\malia\source\repos\EADCA3\EADCA3\_Imports.razor"
using System.Net.Http.Json;

#line default
#line hidden
#nullable disable
#nullable restore
#line 3 "C:\Users\malia\source\repos\EADCA3\EADCA3\_Imports.razor"
using Microsoft.AspNetCore.Components.Forms;

#line default
#line hidden
#nullable disable
#nullable restore
#line 4 "C:\Users\malia\source\repos\EADCA3\EADCA3\_Imports.razor"
using Microsoft.AspNetCore.Components.Routing;

#line default
#line hidden
#nullable disable
#nullable restore
#line 5 "C:\Users\malia\source\repos\EADCA3\EADCA3\_Imports.razor"
using Microsoft.AspNetCore.Components.Web;

#line default
#line hidden
#nullable disable
#nullable restore
#line 6 "C:\Users\malia\source\repos\EADCA3\EADCA3\_Imports.razor"
using Microsoft.AspNetCore.Components.Web.Virtualization;

#line default
#line hidden
#nullable disable
#nullable restore
#line 7 "C:\Users\malia\source\repos\EADCA3\EADCA3\_Imports.razor"
using Microsoft.AspNetCore.Components.WebAssembly.Http;

#line default
#line hidden
#nullable disable
#nullable restore
#line 8 "C:\Users\malia\source\repos\EADCA3\EADCA3\_Imports.razor"
using Microsoft.JSInterop;

#line default
#line hidden
#nullable disable
#nullable restore
#line 10 "C:\Users\malia\source\repos\EADCA3\EADCA3\_Imports.razor"
using EADCA3.Shared;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "C:\Users\malia\source\repos\EADCA3\EADCA3\Pages\Index.razor"
using System.Runtime.Serialization;

#line default
#line hidden
#nullable disable
#nullable restore
#line 4 "C:\Users\malia\source\repos\EADCA3\EADCA3\Pages\Index.razor"
using EADCA3;

#line default
#line hidden
#nullable disable
    [Microsoft.AspNetCore.Components.RouteAttribute("/")]
    public partial class Index : Microsoft.AspNetCore.Components.ComponentBase
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
        }
        #pragma warning restore 1998
#nullable restore
#line 49 "C:\Users\malia\source\repos\EADCA3\EADCA3\Pages\Index.razor"
       
    private Root data;
    private bool found;
    private string name;
    private List<Result> title { get; set; } = new List<Result>() { };

    private async Task DataforAutofinish()
    {
        var client = new HttpClient();
        var request = new HttpRequestMessage
        {
            Method = HttpMethod.Get,
            RequestUri = new Uri("https://imdb8.p.rapidapi.com/title/find?q=Lost"),
            Headers =
{
    { "x-rapidapi-host", "imdb8.p.rapidapi.com" },
    { "x-rapidapi-key", "b2f2e23b4amsh415f1b5e5a53aa8p1391a0jsn36ef6dc810ec" },
    },
        };
        using (var response = await client.SendAsync(request))
        {
            {
                response.EnsureSuccessStatusCode();
                Root results = await response.Content.ReadFromJsonAsync<Root>();
                Console.WriteLine(data);

                }
            }

        }
        protected override async Task OnInitializedAsync()
        {
            await DataforAutofinish();

        }
        // Root xxDeserializedClass = JsonConvert.DeserializeObject<Root>

        private async Task ButtononClick()
        {
            try
            {
                var client = new HttpClient();
                var request = new HttpRequestMessage
                {
                    Method = HttpMethod.Get,
                    RequestUri = new Uri("https://imdb8.p.rapidapi.com/title/find?q=" + name),
                    Headers =
{
    { "x-rapidapi-host", "imdb8.p.rapidapi.com" },
    { "x-rapidapi-key", "b2f2e23b4amsh415f1b5e5a53aa8p1391a0jsn36ef6dc810ec" },
    },
                };
                using (var response = await client.SendAsync(request))
                {
                    response.EnsureSuccessStatusCode();
                    data = await response.Content.ReadFromJsonAsync<Root>();
                    found = true;
                    Console.WriteLine(data.results);

                    foreach (var t in data.results)
                    {
                        if (t.year != 0)
                        {
                            title.Add(new Result { id = t.id, title = t.title, year = t.year });
                        }
                    }
                }

            }
            catch (Exception)
            {
                found = false;
            }

        }
    

#line default
#line hidden
#nullable disable
        [global::Microsoft.AspNetCore.Components.InjectAttribute] private HttpClient Http { get; set; }
    }
}
#pragma warning restore 1591
